### PR TITLE
add volatilePico

### PR DESCRIPTION
**Pull request by Bettelstab**
## Pull request checklist

- [x] All tests pass. Demo project builds and runs.
- [x] I have resolved any merge conflicts.

## What's in this pull request?

Adds `volatilePico`.

### CODE REVIEW

**Comment by Smittyvb** [comment]
What is Pico consensus?

**Comment by Bettelstab** [comment]
It's a replacement for Nano consensus, further reducing time to connect to the network while keeping the same API. But it has to be tested yet.

**Comment by Bettelstab** [comment]
Seems not to be needed anymore to run multiple instances.

**Comment by styppo** [comment]
Superseded by new PicoConsensus implementation.

**Pull request closed without merging**
